lib/code_climate/test_reporter/configuration.rb
This gets rid of the following warnings:
```
codeclimate-test-reporter-0.4.5/lib/code_climate/test_reporter/configuration.rb:28:
warning: method redefined; discarding old logger
codeclimate-test-reporter-0.4.5/lib/code_climate/test_reporter/configuration.rb:32:
warning: method redefined; discarding old profile
```
=> Eliminate method redefinition warnings

lib/code_climate/test_reporter/git.rb, spec/lib/git_spec.rb
This prevents exceptions (and possibly worse) when attempting to execute git against repositories whose path contains a space.
Note that this doesn't try to protect against stranger cases, like directory names that contain double-quotes, but I'm not familiar with all the special characters that would need to be escaped here.
=> Quote git_dir when used in git command execution

.gitignore, lib/code_climate/test_reporter/git.rb, spec/lib/git_spec.rb
After setting up code climate in my non-rails app I noticed that I was not transmitting the coverage report up to codeclimate due to some bad/wrong code that relied on `defined?` and `Rails.root` incorrectly.
The "fix" for the `Rails.root` support also didn't have tests.
So, I added a fix to support non rails and wrote tests to make sure that we wouldn't have trouble going forward.
Here is the original exception:
Coverage = 100.0%. Code Climate encountered an exception: NoMethodError
undefined method `root' for Rails:Module
/home/ubuntu/census/vendor/bundle/ruby/1.9.1/gems/codeclimate-test-reporter-0.4.6/lib/code_climate/test_reporter/git.rb:61:in `rails_git_dir_present?'
/home/ubuntu/census/vendor/bundle/ruby/1.9.1/gems/codeclimate-test-reporter-0.4.6/lib/code_climate/test_reporter/git.rb …
=> Fixed bug preventing non-rails apps to fail to transfer coverage to code climate

bin/cc-tddium-post-worker, codeclimate-test-reporter.gemspec, spec/lib/ci_spec.rb, spec/lib/client_spec.rb, spec/lib/formatter_spec.rb, spec/spec_helper.rb
@calavera 
using webmock since it has the nice sideeffect of blowing up when a request is done by accident
also we no longer need to declare a custom rack endpoint :)
dropping rubygems requires since they are not needed on 1.9+
adding test for untested batch_post_results
=> cleanup + tests

lib/code_climate/test_reporter/formatter.rb, spec/lib/formatter_spec.rb
=> deprecate TO_FILE and make all private methods private

lib/code_climate/test_reporter.rb
This message isn't very useful to see on every test run so I'd rather 'hide' it at the debug log level or drop the log message completely.
In fact, perhaps it makes more sense to log a message when `CODECLIMATE_REPO_TOKEN` *is* set?
=> log message when sending coverage report

lib/code_climate/test_reporter/ci.rb
Hi! Our clients want to use this gem inside our CI (https://vexor.io), so this commit is supposed to add support for it.
=> Added Vexor.io to the list of CIs.

lib/code_climate/test_reporter/ci.rb
Buildbox was renamed to Buildkite [last year](https://buildkite.com/blog/introducing-our-new-name), and all new customers since then won't have these old `BUILDBOX_*` environment variables.
This change renames them all to the correct `BUILDKITE_*` environment variables, which everyone has available in the their builds.
=> Rename Buildbox to Buildkite

README.md
README's `SimpleCov::Formatter::MultiFormatter.[]` is little bit old.
I was displayed following.
```
[DEPRECATION] ::[] is deprecated. Use ::new instead
```
=> Remove simplecov's deprecation warning

.travis.yml, circle.yml
=> Move from Travis to Circle

lib/code_climate/test_reporter/formatter.rb, spec/lib/formatter_spec.rb
Ignore skipped lines specified via `:nocov:`
=> Ignore skipped lines

lib/code_climate/test_reporter/formatter.rb, spec/lib/formatter_spec.rb
If you have a rails app in a directory named `/app`, you will remove too
much. Make sure we're only removing the first instance of it.
@codeclimate/review
=> Don't remove the simplecov root more than once

lib/code_climate/test_reporter/ci.rb
This mapping is misconfigured to use the CI build number for git commit sha, as
reported in https://github.com/codeclimate/python-test-reporter/issues/23.
@codeclimate/review :mag_right:
=> Fix Drone CI commit_sha inference

lib/code_climate/test_reporter/client.rb
This is important when you self-host CodeClimate and use your own certificate. The one in the repo is over 3 years old and can't cover all self-signed certificates either.
=> Respect SSL_CERT_FILE environment variable

circle.yml
@codeclimate/review this is changes our CI tests to run against both 1.9.3 and 2.2.2 for a bit more assurance of compatibility.
=> test on both 1.9.3 and 2.2.2

lib/code_climate/test_reporter/formatter.rb, spec/lib/formatter_spec.rb
It's something that we can no longer infer, now that we're running our
test reporter code separately from the tests themselves.
Or, if we want to infer it, we can't infer it based on the current
process, which is what simplecov will try to do:
https://github.com/colszowka/simplecov/blob/6e5ec2342cc1cfea16ca6c3bb1034062267defbf/lib/simplecov/command_guesser.rb#L43-L56
I don't _think_ that we need to include this, and I'm trying to verify
how we use it.
See https://github.com/codeclimate/ruby-test-reporter/issues/135 for some more context on how this manifests to users.
=> Stop sending the test framework

README.md
I noticed that we need to upgrade some things in our repo, but if you just read the `Upgrading from pre-1.0 Versions` as written, it's hard to tell exactly what needs to change.  It's also easy to miss part of the first bullet because it is technically two separate steps mixed into one bullet.  So as you change the code for the first half, you forget to go back and do the second half.
This clarifies those steps a bit, and separates the first bullet into two separate bullets.
=> Clarify upgrade instructions

README.md
The majority of repos won't need to customize beyond this, and for those
who want to, the link is there.
=> Inline the SimpleCov.start to README

lib/code_climate/test_reporter/shorten_filename.rb, spec/lib/shorten_filename_spec.rb
Without escaping the root, the absolute paths remain absolute and then
our validation rejects the test file reports and the user is told their
report is invalid.
This can occur when run in a local environment or on a service such as
Jenkins.
@codeclimate/review
=> Escape SimpleCov.root to allow folders with parens

.gitignore, Gemfile, Gemfile.ruby-19, bin/ci, circle.yml, codeclimate-test-reporter.gemspec
* move development dependencies to Gemfile
* use bundler's platform directive to specify ruby version dependency
differences
* promote SimpleCov to a runtime depenency
Inspired by:
* https://github.com/codeclimate/ruby-test-reporter/commit/a0e5d038dfbcaed56e5b7b2b30a7ec2ab1c468db#commitcomment-19735625
* https://github.com/codeclimate/ruby-test-reporter/issues/146#issuecomment-259260662
@codeclimate/review @dblandin
=> Audit and organize dependencies

CHANGELOG.md, README.md, codeclimate-test-reporter.gemspec
Also updated the release process (mostly copied from minidoc) to
emphasize the importance of updating the changelog
Moved the 1.0.0 upgrade instructions into the changelog. Left the
section, because we linked to it in some places, and I don't want to
break those links.
Didn't document the changelog going back all the way to the beginning.
We could fill that in, but I don't think it's urgent.
Close #152
=> Add changelog

bin/codeclimate-test-reporter
=> refactor start script and add option for custom coverage result path

bin/ci
We don't recommend against this, and it allows community-contributed PRs
to have their coverage reported from Circle CI builds.
=> Hard-code CODECLIMATE_REPO_TOKEN

lib/code_climate/test_reporter/ci.rb
For https://github.com/codeclimate/ruby-test-reporter/issues/156.
Plus correct build identifier, `CI_BUILD_NUMBER` does not exist in
codeship.
=> Wire committed_at to ci_timestamp for codeship

lib/code_climate/test_reporter/git.rb
This is fixing the issue that code coverage is not reported correctly when `.git` folder is not present.
Related issues:
**command not found: git** - https://github.com/codeclimate/ruby-test-reporter/issues/171
**Feature - run on Codeship out of the box** - https://github.com/codeclimate/ruby-test-reporter/issues/156
**CodeClimate::TestReporter::Git doesn't use branch_from_git_or_ci** - https://github.com/codeclimate/ruby-test-reporter/issues/115
=> Get commit hash from CI if failed to get it from Git

README.md
Thought this usage section would be useful to have. We don't mention the env var anywhere in README or our docs.
=> Add execution example and mention optional env

CHANGELOG.md, codeclimate-test-reporter.gemspec, lib/code_climate/test_reporter/version.rb
Done because the 0.14.0 version introduces some changes that break the
`CodeClimate::TestReporter::Formatter#merge_results`
https://github.com/colszowka/simplecov/commit/a7747c1391b7f8d0b7081c23df79b151ebbc95bd
Check also:
* SimpleCov::Result - https://github.com/colszowka/simplecov/blob/v0.14.0/lib/simplecov/result.rb
* SimpleCov::RawCoverage - https://github.com/colszowka/simplecov/blob/v0.14.0/lib/simplecov/raw_coverage.rb
=> Lock simplecov between 0.10 and 0.13 version
